name: run-docker-image

on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        
    # TODO: 1. Connect to k8s cluster + private docker registry
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
      - name: Start minikube
        uses: medyagh/setup-minikube@master
        
      - name: Try the cluster
        run: kubectl get pods -A

      # TODO: 2. Create docker image (nginx web server + php-fpm with index.php inside)

      # 3. Upload the image to the docker registry.

      # 4. Pull the image from the docker registry and deploy it to the kubernetes cluster.

      # 5. For branch develop, the deploy is done automatically on pull request while for
          # branch master the deploy is done by running the workflow manually.
      
      # 6. The workflow should output the applicationâ€™s service external ip.
      
      # - name: Pull Docker image
      #   run: docker pull guypeeril/llay-home-test:v2.0

      # - name: Run Docker image
      #   run: docker run -d -p 80:80 guypeeril/llay-home-test:v2.0
